version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - localstack
    networks:
      - localstack-network
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    env_file:
      - .env
    environment:
      - SERVICES=s3,dynamodb
    networks:
      - localstack-network

networks:
  localstack-network:
    driver: bridge
